//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18046
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaicaiWallpaper.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaicaiWallpaper.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 选择图片库中的图片，并将本应用设置为锁屏界面， 的本地化字符串。
        /// </summary>
        public static string AboutContent1 {
            get {
                return ResourceManager.GetString("AboutContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 便可以定时在您的图片列表中切换锁屏壁纸， 的本地化字符串。
        /// </summary>
        public static string AboutContent2 {
            get {
                return ResourceManager.GetString("AboutContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让您的屏幕不在单调~ 的本地化字符串。
        /// </summary>
        public static string AboutContent3 {
            get {
                return ResourceManager.GetString("AboutContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用我这么久了，给个好评呗亲~ 的本地化字符串。
        /// </summary>
        public static string AboutContentHaopingContent {
            get {
                return ResourceManager.GetString("AboutContentHaopingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给个好评呗~ 的本地化字符串。
        /// </summary>
        public static string AboutContentHaopingTitle {
            get {
                return ResourceManager.GetString("AboutContentHaopingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱动壁纸 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再按一次后退键退出程序 的本地化字符串。
        /// </summary>
        public static string MainBackNotice {
            get {
                return ResourceManager.GetString("MainBackNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要清除所有图像吗？ 的本地化字符串。
        /// </summary>
        public static string MainClearImage {
            get {
                return ResourceManager.GetString("MainClearImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理完成~ 的本地化字符串。
        /// </summary>
        public static string MainClearImageDown {
            get {
                return ResourceManager.GetString("MainClearImageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加时间: 的本地化字符串。
        /// </summary>
        public static string MainContentItemAddTime {
            get {
                return ResourceManager.GetString("MainContentItemAddTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意: 的本地化字符串。
        /// </summary>
        public static string MainContentNotice1 {
            get {
                return ResourceManager.GetString("MainContentNotice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法更新壁纸 的本地化字符串。
        /// </summary>
        public static string MainContentNotice10 {
            get {
                return ResourceManager.GetString("MainContentNotice10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于系统限制和后台服务的不稳定性， 的本地化字符串。
        /// </summary>
        public static string MainContentNotice11 {
            get {
                return ResourceManager.GetString("MainContentNotice11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 壁纸更换时间可能有一定 的本地化字符串。
        /// </summary>
        public static string MainContentNotice12 {
            get {
                return ResourceManager.GetString("MainContentNotice12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偏差 的本地化字符串。
        /// </summary>
        public static string MainContentNotice13 {
            get {
                return ResourceManager.GetString("MainContentNotice13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这里给大家带来的困扰深感 的本地化字符串。
        /// </summary>
        public static string MainContentNotice14 {
            get {
                return ResourceManager.GetString("MainContentNotice14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱歉 的本地化字符串。
        /// </summary>
        public static string MainContentNotice15 {
            get {
                return ResourceManager.GetString("MainContentNotice15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我会进一步优化和完善， 的本地化字符串。
        /// </summary>
        public static string MainContentNotice16 {
            get {
                return ResourceManager.GetString("MainContentNotice16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为大家做得更好！ 的本地化字符串。
        /// </summary>
        public static string MainContentNotice17 {
            get {
                return ResourceManager.GetString("MainContentNotice17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于系统设定的关系， 的本地化字符串。
        /// </summary>
        public static string MainContentNotice2 {
            get {
                return ResourceManager.GetString("MainContentNotice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当开启 的本地化字符串。
        /// </summary>
        public static string MainContentNotice3 {
            get {
                return ResourceManager.GetString("MainContentNotice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省电模式 的本地化字符串。
        /// </summary>
        public static string MainContentNotice4 {
            get {
                return ResourceManager.GetString("MainContentNotice4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台服务过多 的本地化字符串。
        /// </summary>
        public static string MainContentNotice5 {
            get {
                return ResourceManager.GetString("MainContentNotice5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者 的本地化字符串。
        /// </summary>
        public static string MainContentNotice6 {
            get {
                return ResourceManager.GetString("MainContentNotice6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长时间休眠 的本地化字符串。
        /// </summary>
        public static string MainContentNotice7 {
            get {
                return ResourceManager.GetString("MainContentNotice7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等原因时， 的本地化字符串。
        /// </summary>
        public static string MainContentNotice8 {
            get {
                return ResourceManager.GetString("MainContentNotice8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台无法启动，也就 的本地化字符串。
        /// </summary>
        public static string MainContentNotice9 {
            get {
                return ResourceManager.GetString("MainContentNotice9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表已经够多啦~先精选清理一下吧~ 的本地化字符串。
        /// </summary>
        public static string MainImageTooMore {
            get {
                return ResourceManager.GetString("MainImageTooMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记得每隔两周之内启动一下程序哦~ 的本地化字符串。
        /// </summary>
        public static string MainLaunchNotice {
            get {
                return ResourceManager.GetString("MainLaunchNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率： 的本地化字符串。
        /// </summary>
        public static string ModelFenbianlv {
            get {
                return ResourceManager.GetString("ModelFenbianlv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽高比： 的本地化字符串。
        /// </summary>
        public static string ModelKuangaobi {
            get {
                return ResourceManager.GetString("ModelKuangaobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您可以启动&apos;更换壁纸&apos;磁贴 的本地化字符串。
        /// </summary>
        public static string OneKeyContent1 {
            get {
                return ResourceManager.GetString("OneKeyContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或按住“Home”键说&quot;换壁纸&quot; 的本地化字符串。
        /// </summary>
        public static string OneKeyContent2 {
            get {
                return ResourceManager.GetString("OneKeyContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一键换壁纸 的本地化字符串。
        /// </summary>
        public static string OneKeyContent3 {
            get {
                return ResourceManager.GetString("OneKeyContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （该页面下次将不会出现） 的本地化字符串。
        /// </summary>
        public static string OneKeyContent4 {
            get {
                return ResourceManager.GetString("OneKeyContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入程序设置为锁屏界面才能自动更换壁纸哦~ 的本地化字符串。
        /// </summary>
        public static string OneKeyNoSetNotice {
            get {
                return ResourceManager.GetString("OneKeyNoSetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换壁纸 的本地化字符串。
        /// </summary>
        public static string OneKeyPinTitle {
            get {
                return ResourceManager.GetString("OneKeyPinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一键切换壁纸 的本地化字符串。
        /// </summary>
        public static string OneKeyTitle {
            get {
                return ResourceManager.GetString("OneKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string PageDown {
            get {
                return ResourceManager.GetString("PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string PageUp {
            get {
                return ResourceManager.GetString("PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勾选中添加进壁纸列表，再次点击删除~ 的本地化字符串。
        /// </summary>
        public static string PicsAddContent1 {
            get {
                return ResourceManager.GetString("PicsAddContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您屏幕的宽高比是 的本地化字符串。
        /// </summary>
        public static string PicsAddContent2 {
            get {
                return ResourceManager.GetString("PicsAddContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,建议选择相近宽高比的图片~ 的本地化字符串。
        /// </summary>
        public static string PicsAddContent3 {
            get {
                return ResourceManager.GetString("PicsAddContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string PicsFoldersTitle {
            get {
                return ResourceManager.GetString("PicsFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-cn 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机切换 的本地化字符串。
        /// </summary>
        public static string SettingFangshi1 {
            get {
                return ResourceManager.GetString("SettingFangshi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序切换 的本地化字符串。
        /// </summary>
        public static string SettingFangshi2 {
            get {
                return ResourceManager.GetString("SettingFangshi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换方式 的本地化字符串。
        /// </summary>
        public static string SettingFangshiTitle {
            get {
                return ResourceManager.GetString("SettingFangshiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须要有个关于页面么？ 的本地化字符串。
        /// </summary>
        public static string SettingGoToAbout {
            get {
                return ResourceManager.GetString("SettingGoToAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换频率 的本地化字符串。
        /// </summary>
        public static string SettingPinlvTitle {
            get {
                return ResourceManager.GetString("SettingPinlvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定才能自动更换壁纸哦~ 的本地化字符串。
        /// </summary>
        public static string SettingSetLockFail {
            get {
                return ResourceManager.GetString("SettingSetLockFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置为锁屏背景 的本地化字符串。
        /// </summary>
        public static string SettingSetLockTitle {
            get {
                return ResourceManager.GetString("SettingSetLockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1小时 的本地化字符串。
        /// </summary>
        public static string SettingTime1 {
            get {
                return ResourceManager.GetString("SettingTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12小时 的本地化字符串。
        /// </summary>
        public static string SettingTime12 {
            get {
                return ResourceManager.GetString("SettingTime12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3小时 的本地化字符串。
        /// </summary>
        public static string SettingTime3 {
            get {
                return ResourceManager.GetString("SettingTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30分钟 的本地化字符串。
        /// </summary>
        public static string SettingTime30 {
            get {
                return ResourceManager.GetString("SettingTime30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6小时 的本地化字符串。
        /// </summary>
        public static string SettingTime6 {
            get {
                return ResourceManager.GetString("SettingTime6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精品应用推荐: 的本地化字符串。
        /// </summary>
        public static string SettingTuijianTitle {
            get {
                return ResourceManager.GetString("SettingTuijianTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台任务被禁止或超出数量，锁屏将无法更新~ 的本地化字符串。
        /// </summary>
        public static string TaskErrToast1 {
            get {
                return ResourceManager.GetString("TaskErrToast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请到&lt;设置-应用程序-后台任务&gt;中进行设置~ 的本地化字符串。
        /// </summary>
        public static string TaskErrToast2 {
            get {
                return ResourceManager.GetString("TaskErrToast2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于定期更换墙纸。记得每隔两周之内启动一下哦~ 的本地化字符串。
        /// </summary>
        public static string TaskNotice {
            get {
                return ResourceManager.GetString("TaskNotice", resourceCulture);
            }
        }
    }
}
